<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Agents.AI" VersionOverride="1.15.0" />
    <PackageReference Include="Microsoft.Agents.AI.Hosting" VersionOverride="1.15.0-preview.260722.1" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" VersionOverride="1.15.0" />
    <PackageReference Include="Azure.AI.OpenAI" VersionOverride="2.9.0-beta.1" />
    <PackageReference Include="Azure.Identity" VersionOverride="1.21.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\samples\AIChat.ClientServer.Sample\AIChat.ClientServer.Sample.Shared\AIChat.ClientServer.Sample.Shared.csproj" />
    <ProjectReference Include="..\..\..\samples\AIChat.ClientServer.Sample\AIChat.ClientServer.Sample.AgentServer\AIChat.ClientServer.Sample.AgentServer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
