const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { createRequire } = require("node:module");
const { test } = require("node:test");
const vm = require("node:vm");

const workflowDir = path.resolve(__dirname, "..");
const source = fs.readFileSync(path.join(workflowDir, "ai-docs-audit.md"), "utf8");
const compiled = fs.readFileSync(path.join(workflowDir, "ai-docs-audit.lock.yml"), "utf8");
const disclosures = {
  create_issue: "AI disclosure: A generative AI model, accessed through GitHub Copilot, determined that the audited documentation may need updating and drafted this issue text. Please verify the recommendation and content before acting.",
  create_pull_request: "AI disclosure: A generative AI model, accessed through GitHub Copilot, determined that the audited documentation may need updating, proposed the documentation changes, and drafted this pull request text. Please verify the recommendation, changes, and content before acting.",
};

function disclosureScript(workflow) {
  const blocks = [...workflow.matchAll(/^( +)script: \|\n((?:\1  .*(?:\n|$)|\n)+)/gm)];
  const scripts = blocks.map(([, indent, body]) =>
    body.replace(new RegExp(`^${indent}  `, "gm"), ""));
  const matches = scripts.filter(script => script.includes("const disclosures = {"));
  assert.equal(matches.length, 1);
  return matches[0];
}

function enforce(script, output) {
  let content = JSON.stringify(output);
  vm.runInNewContext(script, {
    process: { env: { GH_AW_AGENT_OUTPUT: "/fixture/agent_output.json" } },
    require(name) {
      assert.equal(name, "node:fs");
      return {
        readFileSync(file) {
          assert.equal(file, "/fixture/agent_output.json");
          return content;
        },
        writeFileSync(file, value) {
          assert.equal(file, "/fixture/agent_output.json");
          content = value;
        },
      };
    },
  });
  return JSON.parse(content);
}

for (const [name, workflow] of [["source", source], ["compiled", compiled]]) {
  const script = disclosureScript(workflow);
  for (const [type, disclosure] of Object.entries(disclosures)) {
    const notice = `made with AI\n\n${disclosure}`;
    test(`${name}: ${type} gets one visible, idempotent notice without losing provenance`, () => {
      const provenance = "> Generated by [Weekly AI Docs Audit](https://github.com/dotnet/maui-labs/actions/runs/456)";
      const marker = "<!-- gh-aw-workflow-id: ai-docs-audit -->";
      for (const body of [
        "Changes",
        `${notice}\n\nChanges`,
        `Changes\n\n${notice}\n\n${notice}`,
        `<!-- ${notice} -->\n\nChanges`,
        `\`\`\`\n${notice}\n\`\`\`\n\nChanges`,
        `${disclosure}\n\nChanges\n\n${notice}`,
        `made with AI\n\nChanges`,
        `Changes\n\n${notice}\n\n${provenance}\n${marker}`,
      ]) {
        const item = { type, title: "Audit findings", body, patch_path: "/fixture/audit.patch", draft: true };
        const output = { items: [item], metadata: "keep" };
        const result = enforce(script, output);
        const actual = result.items[0].body;
        assert.ok(actual.startsWith(`${notice}\n\n`));
        assert.equal(actual.split("made with AI").length - 1, 1);
        assert.equal(actual.split(disclosure).length - 1, 1);
        assert.ok(actual.includes("Changes"));
        if (body.includes(provenance)) {
          assert.ok(actual.includes(provenance));
          assert.ok(actual.includes(marker));
        }
        assert.deepEqual({ ...result.items[0], body }, item);
        assert.equal(result.metadata, "keep");
        assert.deepEqual(enforce(script, result), result);
      }
    });

    test(`${name}: ${type} long and empty bodies retain prefix without silent truncation`, () => {
      for (const body of ["", "x".repeat(65000)]) {
        const result = enforce(script, { items: [{ type, body }] });
        assert.equal(result.items[0].body, `${notice}\n\n${body}`);
      }
    });
  }

  test(`${name}: unrelated messages and empty outputs are unchanged`, () => {
    const output = { items: [
      { type: "missing_data", reason: "No PR data" },
      { type: "missing_tool", reason: "No tool" },
      { type: "noop", message: "No changes" },
    ] };
    assert.deepEqual(enforce(script, output), output);
    assert.deepEqual(enforce(script, { items: [] }), { items: [] });
  });

  test(`${name}: malformed output fails closed before writing`, () => {
    assert.throws(() => enforce(script, {}), /Expected safe-output items/);
    for (const type of Object.keys(disclosures)) {
      for (const body of [undefined, null, 12, {}]) {
        assert.throws(() => enforce(script, { items: [{ type, body }] }), /Expected an audit output body/);
      }
    }
  });
}

const job = compiled.slice(compiled.indexOf("\n  safe_outputs:"));
const config = JSON.parse(JSON.parse(job.match(/GH_AW_SAFE_OUTPUTS_HANDLER_CONFIG: (".*")/)[1]));
test("compiled hook order and all existing Audit output configuration stay intact", () => {
  assert.equal(disclosureScript(source), disclosureScript(compiled));
  const download = job.indexOf('echo "GH_AW_AGENT_OUTPUT=');
  const enforcement = job.indexOf("id: enforce_ai_disclosure");
  const handler = job.indexOf("id: process_safe_outputs");
  assert.ok(download > 0 && enforcement > download && handler > enforcement);
  assert.doesNotMatch(job.slice(enforcement, handler), /continue-on-error: true|if: always\(\)/);
  assert.deepEqual(config, {
    create_issue: { close_older_issues: true, labels: ["ai-docs-audit"], max: 1, title_prefix: "[ai-docs] " },
    create_pull_request: { draft: true, labels: ["ai-docs-audit"], max: 1, max_patch_size: 1024, title_prefix: "[ai-docs] " },
    missing_data: {},
    missing_tool: {},
  });
  assert.match(job, /needs.agent.outputs.detection_success == 'true'/);
  assert.match(job, /require\('\/opt\/gh-aw\/actions\/safe_output_handler_manager.cjs'\)/);
  for (const type of Object.keys(disclosures)) {
    assert.match(compiled, new RegExp(`"${type}": \\{\\n\\s+"defaultMax": 1,\\n\\s+"fields": \\{\\n\\s+"body": \\{\\n\\s+"required": true,\\n\\s+"type": "string",\\n\\s+"sanitize": true,\\n\\s+"maxLength": 65000`));
  }
});

test("pinned Audit handlers preserve notices, provenance, fallbacks, and caps in API payloads", {
  skip: !process.env.GH_AW_ACTIONS_DIR && "Set GH_AW_ACTIONS_DIR to gh-aw v0.53.5 actions/setup/js",
}, async t => {
  const actionsDir = process.env.GH_AW_ACTIONS_DIR;
  const savedGlobals = { core: global.core, context: global.context, github: global.github };
  const metadata = {
    GH_AW_WORKFLOW_NAME: "Weekly AI Docs Audit",
    GH_AW_WORKFLOW_ID: "ai-docs-audit",
    GH_AW_CALLER_WORKFLOW_ID: "dotnet/maui-labs/ai-docs-audit",
    GH_AW_ENGINE_ID: "copilot",
    GH_AW_SAFE_OUTPUTS_STAGED: "false",
    GITHUB_TOKEN: undefined,
    GH_AW_CI_TRIGGER_TOKEN: undefined,
  };
  const savedEnv = Object.fromEntries(Object.keys(metadata).map(key => [key, process.env[key]]));
  function setEnv(values) {
    for (const [key, value] of Object.entries(values)) {
      if (value === undefined) delete process.env[key];
      else process.env[key] = value;
    }
  }
  t.after(() => { Object.assign(global, savedGlobals); setEnv(savedEnv); });
  setEnv(metadata);
  const summary = { addRaw() { return this; }, async write() {} };
  global.core = { info() {}, debug() {}, warning() {}, error() {}, setOutput() {}, summary };
  global.context = {
    repo: { owner: "dotnet", repo: "maui-labs" }, payload: {},
    serverUrl: "https://github.com", runId: 456,
  };
  let failure;
  const calls = [];
  let searches = 0;
  global.github = { rest: {
    issues: {
      async create(payload) {
        calls.push({ type: "issue", ...payload });
        return { data: { number: 789, html_url: "https://github.com/dotnet/maui-labs/issues/789" } };
      },
      async addLabels(payload) { assert.deepEqual(Array.from(payload.labels), ["ai-docs-audit"]); },
    },
    pulls: {
      async create(payload) {
        if (failure === "permission") throw new Error("GitHub Actions is not permitted to create or approve pull requests");
        if (failure === "pr") throw new Error("Mock PR creation failure");
        calls.push({ type: "pull_request", ...payload });
        return { data: { number: 790, html_url: "https://github.com/dotnet/maui-labs/pull/790" } };
      },
    },
    search: { async issuesAndPullRequests() { searches++; return { data: { items: [] } }; } },
  } };
  const message = (type, body = "Changes") => enforce(disclosureScript(compiled), {
    items: [{ type, title: "Audit findings", body, patch_path: "/fixture/audit.patch" }],
  }).items[0];
  function assertPayload(type, actual) {
    const notice = `made with AI\n\n${disclosures[type]}`;
    assert.ok(actual.body.startsWith(`${notice}\n\n`));
    assert.equal(actual.body.split("made with AI").length - 1, 1);
    assert.match(actual.body, /> Generated by \[Weekly AI Docs Audit\]\(https:\/\/github.com\/dotnet\/maui-labs\/actions\/runs\/456\)/);
    assert.match(actual.body, /<!-- gh-aw-workflow-id: ai-docs-audit -->/);
    assert.equal(actual.owner, "dotnet");
    assert.equal(actual.repo, "maui-labs");
  }
  const issueFactory = require(path.join(actionsDir, "create_issue.cjs")).main;
  const issueHandler = await issueFactory(config.create_issue);
  assert.equal((await issueHandler(message("create_issue"))).success, true);
  assertPayload("create_issue", calls.at(-1));
  assert.match(calls.at(-1).body, /<!-- gh-aw-workflow-call-id: dotnet\/maui-labs\/ai-docs-audit -->/);
  assert.equal(searches, 1, "Older-issue search remains enabled");
  assert.equal((await issueHandler(message("create_issue"))).success, false, "Keep max one issue");

  // Load the actual PR handler with only its direct filesystem/git boundaries mocked.
  const handlerFile = path.join(actionsDir, "create_pull_request.cjs");
  const realRequire = createRequire(handlerFile);
  let patch = "diff --git a/AGENTS.md b/AGENTS.md\n--- a/AGENTS.md\n+++ b/AGENTS.md\n@@ -1 +1 @@\n-old\n+new\n";
  const module = { exports: {} };
  vm.runInNewContext(fs.readFileSync(handlerFile, "utf8"), {
    module, process, Buffer, core: global.core, context: global.context, github: global.github,
    require(name) {
      if (name !== "fs") return realRequire(name);
      return {
        existsSync(file) { assert.equal(file, "/fixture/audit.patch"); return true; },
        readFileSync(file) { assert.equal(file, "/fixture/audit.patch"); return patch; },
      };
    },
    exec: {
      async exec(command) {
        assert.ok(command.startsWith("git "));
        if (failure === "push" && command.startsWith("git push ")) throw new Error("Mock push failure");
        return 0;
      },
      async getExecOutput() { return { stdout: "", stderr: "", exitCode: 0 }; },
    },
  }, { filename: handlerFile });
  const prFactory = module.exports.main;
  for (failure of [undefined, "push", "permission", "pr"]) {
    const handler = await prFactory({ ...config.create_pull_request, base_branch: "main" });
    const notice = `made with AI\n\n${disclosures.create_pull_request}`;
    const result = await handler(message("create_pull_request", `${notice}\n\nChanges\n\n${notice}`));
    assert.equal(result.success, true, JSON.stringify(result));
    assertPayload("create_pull_request", calls.at(-1));
    assert.equal(calls.at(-1).type, failure ? "issue" : "pull_request");
    if (!failure) assert.equal(calls.at(-1).draft, true);
    else assert.equal(result.fallback_used, true);
    assert.equal((await handler(message("create_pull_request"))).success, false, "Keep max one PR");
  }
  failure = undefined;
  for (const [oversizedPatch, error] of [
    ["x".repeat(1024 * 1024 + 1), /Patch size/],
    ["diff --git a/doc b/doc\n".repeat(101), /more than 100 files/],
  ]) {
    patch = oversizedPatch;
    const count = calls.length;
    const handler = await prFactory({ ...config.create_pull_request, base_branch: "main" });
    const result = await handler(message("create_pull_request"));
    assert.equal(result.success, false);
    assert.match(result.error, error);
    assert.equal(calls.length, count);
  }
  for (const boundaryPatch of [
    "x".repeat(1024 * 1024),
    "diff --git a/doc b/doc\n".repeat(100),
  ]) {
    patch = boundaryPatch;
    const handler = await prFactory({ ...config.create_pull_request, base_branch: "main" });
    const result = await handler(message("create_pull_request", "x".repeat(65000)));
    assert.equal(result.success, true, JSON.stringify(result));
    assertPayload("create_pull_request", calls.at(-1));
    assert.ok(calls.at(-1).body.includes("x".repeat(65000)));
  }
});
