const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { test } = require("node:test");
const vm = require("node:vm");

const workflowDir = path.resolve(__dirname, "..");
const source = fs.readFileSync(path.join(workflowDir, "pr-docs-check.md"), "utf8");
const compiled = fs.readFileSync(path.join(workflowDir, "pr-docs-check.lock.yml"), "utf8");
const disclosure = "AI disclosure: A generative AI model, accessed through GitHub Copilot, determined that documentation changes may be needed and drafted this issue. Please verify the recommendation and content before acting.";
const notice = `made with AI\n\n${disclosure}`;

// Execute the actual source and compiled hook without filesystem or GitHub side effects.
function disclosureScript(workflow) {
  const blocks = [...workflow.matchAll(/^( +)script: \|\n((?:\1  .*(?:\n|$)|\n)+)/gm)];
  const scripts = blocks.map(([, indent, body]) =>
    body.replace(new RegExp(`^${indent}  `, "gm"), ""));
  const matches = scripts.filter(script => script.includes(`const disclosure = "${disclosure}";`));
  assert.equal(matches.length, 1, "Exactly one deterministic disclosure step is required");
  return matches[0];
}

function enforce(script, output) {
  let content = JSON.stringify(output);
  vm.runInNewContext(script, {
    process: { env: { GH_AW_AGENT_OUTPUT: "/fixture/agent_output.json" } },
    require(name) {
      assert.equal(name, "node:fs");
      return {
        readFileSync(file, encoding) {
          assert.equal(file, "/fixture/agent_output.json");
          assert.equal(encoding, "utf8");
          return content;
        },
        writeFileSync(file, value, encoding) {
          assert.equal(file, "/fixture/agent_output.json");
          assert.equal(encoding, "utf8");
          content = value;
        },
      };
    },
  });
  return JSON.parse(content);
}

for (const [name, workflow] of [["source", source], ["compiled", compiled]]) {
  const script = disclosureScript(workflow);

  test(`${name}: missing disclosure is prepended without changing content or metadata`, () => {
    const body = "### Source PR\nhttps://github.com/dotnet/maui-labs/pull/123\n\n### Suggested Changes\nDocument the new command.";
    const item = { type: "create_issue", title: "New command", body, repo: "dotnet/docs-maui", labels: ["docs-from-code"] };
    const result = enforce(script, { items: [item], metadata: "preserve" });
    assert.deepEqual(result, {
      items: [{ ...item, body: `${notice}\n\n${body}` }],
      metadata: "preserve",
    });
  });

  test(`${name}: existing and duplicate disclosures normalize to one visible notice`, () => {
    const provenance = "> Generated by [PR Documentation Check](https://github.com/dotnet/maui-labs/actions/runs/123)";
    const marker = "<!-- gh-aw-workflow-call-id: dotnet/maui-labs/pr-docs-check -->";
    for (const body of [
      `${disclosure}\n\nChanges`,
      `Changes\n\n${disclosure}`,
      `${disclosure}\n\nChanges\n\n${disclosure}`,
      `<!-- ${disclosure} -->\n\nChanges`,
      `\`\`\`\n${disclosure}\n\`\`\`\n\nChanges`,
      `Changes\n\n${disclosure}\n\n${provenance}\n${marker}`,
      `${notice}\n\nChanges`,
      `Changes\n\n${notice}`,
      `${notice}\n\nChanges\n\n${notice}`,
      `<!-- ${notice} -->\n\nChanges`,
      `\`\`\`\n${notice}\n\`\`\`\n\nChanges`,
      `${notice}\n\nChanges\n\n${disclosure}`,
      `made with AI\n\nChanges`,
      `Changes\n\n${notice}\n\n${provenance}\n${marker}`,
    ]) {
      const output = { items: [{ type: "create_issue", body }] };
      const result = enforce(script, output);
      const actual = result.items[0].body;
      assert.ok(actual.startsWith(`${notice}\n\n`));
      assert.equal(actual.split(notice).length - 1, 1);
      assert.equal(actual.split("made with AI").length - 1, 1);
      assert.equal(actual.split(disclosure).length - 1, 1);
      assert.ok(actual.includes("Changes"));
      if (body.includes(provenance)) {
        assert.ok(actual.includes(provenance));
        assert.ok(actual.includes(marker));
      }
      assert.deepEqual(enforce(script, result), result, "Reprocessing must be idempotent");
    }
  });

  test(`${name}: long body keeps disclosure first and does not silently truncate content`, () => {
    const body = "x".repeat(65000);
    const actual = enforce(script, { items: [{ type: "create_issue", body }] }).items[0].body;
    assert.equal(actual, `${notice}\n\n${body}`);
  });

  test(`${name}: empty output and non-issue messages are unchanged`, () => {
    for (const output of [
      { items: [] },
      { items: [{ type: "missing_data", reason: "PR not available" }] },
      { items: [{ type: "missing_tool", reason: "Tool not available" }] },
    ]) {
      assert.deepEqual(enforce(script, output), output);
    }
  });

  test(`${name}: malformed output and unsupported updates fail closed`, () => {
    assert.throws(() => enforce(script, {}), /Expected safe-output items/);
    assert.throws(() => enforce(script, { items: [{ type: "create_issue" }] }), /Expected a documentation issue body/);
    assert.throws(() => enforce(script, { items: [{ type: "update_issue", body: "Replacement" }] }), /Issue updates are not supported/);
  });
}

test("compiled output enforces disclosure after download and before the unchanged issue handler", () => {
  assert.equal(disclosureScript(source), disclosureScript(compiled));
  const job = compiled.slice(compiled.indexOf("\n  safe_outputs:"));
  const download = job.indexOf('echo "GH_AW_AGENT_OUTPUT=');
  const enforcement = job.indexOf("id: enforce_ai_disclosure");
  const handler = job.indexOf("id: process_safe_outputs");
  assert.ok(download > 0 && enforcement > download && handler > enforcement);
  assert.doesNotMatch(job.slice(download, handler), /continue-on-error: true|if: always\(\)/);
  const configLine = job.match(/GH_AW_SAFE_OUTPUTS_HANDLER_CONFIG: (".*")/)[1];
  const config = JSON.parse(JSON.parse(configLine));
  assert.deepEqual(Object.keys(config).sort(), ["create_issue", "missing_data", "missing_tool"]);
  assert.equal(config.create_issue["target-repo"], "dotnet/docs-maui");
  assert.equal(config.create_issue.max, 1);
  assert.equal(config.create_issue.footer, undefined, "Keep the default provenance footer");
  assert.equal(config.create_issue.group, undefined, "No unprotected parent issue creation");
  assert.match(job, /require\('\/opt\/gh-aw\/actions\/safe_output_handler_manager.cjs'\)/);
});

test("pinned gh-aw handler sends disclosure and provenance in the actual create payload", {
  skip: !process.env.GH_AW_ACTIONS_DIR && "Set GH_AW_ACTIONS_DIR to gh-aw v0.53.5 actions/setup/js",
}, async t => {
  const { main } = require(path.join(process.env.GH_AW_ACTIONS_DIR, "create_issue.cjs"));
  const savedGlobals = { core: global.core, context: global.context, github: global.github };
  const metadata = {
    GH_AW_WORKFLOW_NAME: "PR Documentation Check",
    GH_AW_WORKFLOW_ID: "pr-docs-check",
    GH_AW_CALLER_WORKFLOW_ID: "dotnet/maui-labs/pr-docs-check",
    GH_AW_ENGINE_ID: "copilot",
    GH_AW_SAFE_OUTPUTS_STAGED: "false",
  };
  const savedEnv = Object.fromEntries(Object.keys(metadata).map(key => [key, process.env[key]]));
  t.after(() => {
    Object.assign(global, savedGlobals);
    for (const [key, value] of Object.entries(savedEnv)) {
      if (value === undefined) delete process.env[key];
      else process.env[key] = value;
    }
  });
  Object.assign(process.env, metadata);
  global.core = { info() {}, debug() {}, warning() {}, setOutput() {}, error(message) { throw new Error(message); } };
  global.context = {
    repo: { owner: "dotnet", repo: "maui-labs" },
    payload: { pull_request: { number: 123 } },
    serverUrl: "https://github.com",
    runId: 456,
  };
  const calls = [];
  global.github = {
    rest: {
      issues: {
        async create(payload) {
          calls.push(payload);
          return { data: { number: 789, html_url: "https://github.com/dotnet/docs-maui/issues/789" } };
        },
      },
    },
  };

  for (const body of ["Changes", `${disclosure}\n\nChanges`, `${notice}\n\nChanges\n\n${notice}`, "x".repeat(65000)]) {
    const handler = await main({
      "target-repo": "dotnet/docs-maui",
      title_prefix: "[maui-labs docs] ",
      labels: ["docs-from-code"],
      max: 1,
    });
    const output = enforce(disclosureScript(compiled), {
      items: [{ type: "create_issue", title: "New command", body }],
    });
    const result = await handler(output.items[0]);
    assert.equal(result.success, true);
    const actual = calls.at(-1);
    assert.equal(actual.owner, "dotnet");
    assert.equal(actual.repo, "docs-maui");
    assert.ok(actual.body.startsWith(`${notice}\n\n`));
    assert.equal(actual.body.split("made with AI").length - 1, 1);
    assert.equal(actual.body.split(disclosure).length - 1, 1);
    assert.match(actual.body, /> Generated by \[PR Documentation Check\]\(https:\/\/github.com\/dotnet\/maui-labs\/actions\/runs\/456\)/);
    assert.match(actual.body, /<!-- gh-aw-workflow-call-id: dotnet\/maui-labs\/pr-docs-check -->/);
    assert.match(actual.body, /engine: copilot/);
  }
  assert.equal(calls.length, 4);
});
