name: CI - AI Extensions

on:
  push:
    branches: [main]
    paths:
      - 'src/AIExtensions/**'
      - 'tests/AIExtensions/**'
      - 'samples/AIExtensions.Sample.ChatPlayground/**'
      - 'eng/**'
      - 'Directory.Build.props'
      - 'Directory.Build.targets'
      - 'Directory.Packages.props'
      - 'global.json'
      - 'NuGet.config'
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]
    paths:
      - 'src/AIExtensions/**'
      - 'tests/AIExtensions/**'
      - 'samples/AIExtensions.Sample.ChatPlayground/**'
      - 'eng/**'
      - 'Directory.Build.props'
      - 'Directory.Build.targets'
      - 'Directory.Packages.props'
      - 'global.json'
      - 'NuGet.config'

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      project-path: src/AIExtensions/AIExtensions.Packages.slnf
      project-name: ai-extensions
      run-tests: true
      pack: true
      install-workloads: false

  sample:
    uses: ./.github/workflows/_build.yml
    with:
      project-path: samples/AIExtensions.Sample.ChatPlayground/AIExtensions.Sample.ChatPlayground.csproj
      project-name: ai-chat-playground
      os: '["macos-latest"]'
      run-tests: false
      pack: false
      install-workloads: true
      xcode-version: '26.3'
      android-project: src/AI/Microsoft.Maui.Essentials.AI/Microsoft.Maui.Essentials.AI.csproj
